version: '3.4'
services:
  syslog-ng:
    build: ./syslog-ng
    image: balabit_syslog-ng
    container_name: syslog-ng-teste
    ports:
    - 514:514/udp
    - 601:601/tcp
    - 6514:6514/tcp
    volumes:
    - ./log:/var/log

  elk:
    image: sebp/elk
    container_name: elk_container_test
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    depends_on:
    - syslog-ng

  # rsyslog:
  #   build: ./rsyslog
  #   container_name: rsyslog_container_test
  #   image: rsyslog_imagem
  #   environment:
  #   - "TZ=America/Sao_Paulo" # (-03, -0300)
  #   ports:
  #   - 514:514/udp
  #   volumes:
  #   - ./log:/var/log
  #   - ./rsyslog/rsyslog.d:/etc/rsyslog.d
