version: '3.4'
services:
  # ELK
  elk:
    #image: sebp/elk:8.3.3
    build:
      context: ./elk/
    image: elk_img
    container_name: elk_dev_0
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5959:5959/udp"
    volumes:
    - ./data/elk:/var/lib/elasticsearch                 # volume data elastic
    - ./data/logstash_debug:/mnt:Z                        # debug json resume
    #- ./logstash/pipeline:/usr/share/logstash  # cfg logstash python


  # filebeat:
  #   image: prima/filebeat
  #   volumes:
  #   - ./filebeat/filebeat.yml:/filebeat.yml
  #   - ./data/logs:/var/log
  #   depends_on:
  #   - logstash

  # # Syslog
  # syslog-ng:
  #   build: ./syslog-ng
  #   image: balabit_syslog-ng
  #   container_name: syslog-ng-teste
  #   depends_on:
  #   - elasticsearch
  #   ports:
  #   - 514:514/udp
  #   - 601:601/tcp
  #   - 6514:6514/tcp
  #   volumes:
  #   - ./data/logs:/var/log
    
  # # Redis
  # redis:
  #   build: ./redis
  #   container_name: redis_container
  #   image: redis_image
  #   # logging:
  #   #   driver: syslog
  #   #   options:
  #   #     syslog-address: udp://127.0.0.1:514
  #   ports:
  #   - 6379:6379
  #   # depends_on:
  #   # - syslog-ng
  #   volumes:
  #   - ./data/redis:/data

  # # WEB 
  # nginx:
  #   container_name: nginx_container
  #   image: nginx
  #   # depends_on:
  #   # - syslog-ng
  #   # logging:
  #   #   driver: syslog
  #   #   options:
  #   #     syslog-address: udp://127.0.0.1:514
  #   volumes:
  #   - /home/nfs_dsk/data:/usr/share/nginx/html
  #   - ./nginx/conf.d:/etc/nginx/conf.d
  #   ports:
  #   - 5080:80

  # rsyslog:
  #   build: ./rsyslog
  #   container_name: rsyslog_container_test
  #   image: rsyslog_imagem
  #   environment:
  #   - "TZ=America/Sao_Paulo" # (-03, -0300)
  #   ports:
  #   - 514:514/udp
  #   volumes:
  #   - ./log:/var/log
  #   - ./rsyslog/rsyslog.d:/etc/rsyslog.d
